---
title: ""
description: ""
author: 
    - name: "Ítalo Marques-Monteiro"
    - email: "italo.marques.monteiro@outlook.com"
date: "02 set 2023"
output: html_document
---

```{r}
library(tidyverse)
```

```{r}
reb <- sidrar::get_sidra(
    api = "/t/3939/n6/all/v/all/p/last%201/c79/2670,2672,2675,2677,2680,2681,32793,32794") |>
    janitor::clean_names("snake") |>
    dplyr::glimpse()
```

```{r}
reb <- reb |>
    dplyr::select(
        municipio_codigo, municipio, tipo_de_rebanho, valor) |>
    tidyr::separate(
        col = municipio, into = c(
            "municipio", "abbrev_state"), sep = " - ") |>
    dplyr::glimpse()
```

```{r}
reb <- reb |>
    dplyr::mutate(code_muni = as.double(code_muni)) |>
    dplyr::glimpse()
```


dados espaciais 
```{r}
muni <- geobr::read_municipality(code_muni = "all", year = 2020)
muni |> dplyr::glimpse()
```

```{r}
rebanho <- muni |>
    dplyr::left_join(reb) |>
    dplyr::glimpse() 
rebanho |> tibble::view()
```


tabela-ranking e mapa de bovinos
```{r}
reb |>
    dplyr::filter(
        abbrev_state == "RS" &
            tipo_de_rebanho == "Bovino" & valor > 153000
    ) |>
    dplyr::mutate(cab = valor / 1000) |>
    dplyr::select(municipio, cab) |>
    dplyr::arrange(desc(cab))


rank_table_bovino <- tibble::tribble(
    ~cidade,	~efetivo,
    "Alegrete",	524.005,
    "Sant'ana Do Livramento",	498.789,
    "Uruguaiana",	324.526,
    "Dom Pedrito", 309.119,
    "Rosário Do Sul", 263.967,
    "São Gabriel", 254.901,
    "Quaraí", 240.329,
    "Bagé", 223.060,
    "Lavras Do Sul", 168.201,
    "Santiago", 163.484)

cond_table_bovino <- formattable::formattable(rank_table_bovino,
                    col.names = c("Cidade - Ranking", "Efetivo (mil cabeças)"),
                        list(efetivo = formattable::color_tile(
                            "#1f9e89", "#fde725")),
                                align = c("c", "c")
    )
formattable::as.htmlwidget(cond_table_bovino, width = 400)


bovinos <- rebanho |>
    dplyr::filter(
        abbrev_state == "RS" &
            tipo_de_rebanho == "Bovino"
            ) |> #dplyr::arrange(desc(valor))
    ggplot2::ggplot() +
        geom_sf(aes(fill = valor / 1000, na.rm = TRUE)) +
    viridis::scale_fill_viridis(discrete = FALSE) +
        theme_void() +
        labs(
            title = "Efetivo bovino do Rio Grande do Sul",
            subtitle = "IBGE [Pesquisa pecuária municipal (2021) 2023] & geobr (2019) 
            by Ítalo Monteiro ",
        fill = "Número\n[mil cabeças]") +
        theme(
            plot.title = element_text(
                face = "italic", size = 25, hjust = 0.1),
            plot.subtitle = element_text(
                family = "italic", size = 15, color = "gray50", hjust = 0.1),
            plot.caption = element_text(
                face = "italic", size = 12, color = "gray50"),
            axis.text.y = element_blank(),
            #axis.text.y = element_text(
                #size = 14, hjust = 1, family = "Fira Sans"),
            plot.margin = margin(rep(15, 4)),
            panel.background = element_blank(),
            plot.background = element_blank()
        )
bovinos
```

```{r}
ggsave("Image/bovinos.png", plot = bovinos, dpi = 600)
```


tabela-ranking e mapa de equinos
```{r}
reb |>
    dplyr::filter(
        abbrev_state == "RS" &
            tipo_de_rebanho == "Equino" & valor > 7300
    ) |>
    dplyr::mutate(cab = valor / 1000) |>
    dplyr::select(municipio, cab) |>
    dplyr::arrange(desc(cab))


rank_table_equino <- tibble::tribble(
    ~cidade,	~efetivo,
    "Sant'Ana do Livramento", 25.341,
    "Uruguaiana", 21.699,
    "Alegrete", 21.207,
    "Dom Pedrito", 15.128,
    "Bagé", 14.719,
    "São Gabriel", 11.795,
    "Quaraí", 11.492,
    "Rosário do Sul", 11.210,
    "Lavras do Sul",  8.923,
    "Aceguá",  7.374
)

cond_table_equino <- formattable::formattable(rank_table_equino,
                    col.names = c("Cidade - Ranking", "Efetivo (mil cabeças)"),
                        list(efetivo = formattable::color_tile(
                            "#1f9e89", "#fde725")),
                                align = c("c", "c")
    )
formattable::as.htmlwidget(cond_table_equino, width = 400)


equinos <- rebanho |>
    dplyr::filter(
        abbrev_state == "RS" &
            tipo_de_rebanho == "Equino"
            ) |>
    ggplot2::ggplot() +
        geom_sf(aes(fill = valor/1000, na.rm = TRUE)) +
    viridis::scale_fill_viridis(discrete = FALSE) +
        theme_void() +
        labs(
            title = "Efetivo equino do Rio Grande do Sul",
            subtitle = "IBGE [Pesquisa pecuária municipal (2021) 2023] & geobr (2019) 
            by Ítalo Monteiro ",
        fill = "Número\n[mil cabeças]") +
        theme(
            plot.title = element_text(
                face = "italic", size = 25, hjust = 0.1),
            plot.subtitle = element_text(
                family = "italic", size = 15, color = "gray50", hjust = 0.1),
            plot.caption = element_text(
                face = "italic", size = 12, color = "gray50"),
            axis.text.y = element_blank(),
            #axis.text.y = element_text(
                #size = 14, hjust = 1, family = "Fira Sans"),
            plot.margin = margin(rep(15, 4)),
            panel.background = element_blank(),
            plot.background = element_blank()
        )
equinos
```

```{r}
ggsave("Image/equinos.png", plot = equinos, dpi = 600)
```

tabela-ranking e mapa de ovinos
```{r}
reb |>
    dplyr::filter(
        abbrev_state == "RS" &
            tipo_de_rebanho == "Ovino" & valor > 80000
    ) |>
    dplyr::mutate(cab = valor / 1000) |>
    dplyr::select(municipio, cab) |>
    dplyr::arrange(desc(cab))


rank_table_ovino <- tibble::tribble(
    ~cidade,	~efetivo,
    "Sant'Ana do Livramento", 300.026,
    "Alegrete", 193.700,
    "Quaraí", 155.502,
    "Uruguaiana", 149.164,
    "Rosário do Sul", 112.332,
    "Pinheiro Machado", 111.366,
    "Dom Pedrito",  97.822,
    "Bagé",  91.899,
    "Piratini",  83.226,
    "São Gabriel",  82.379
)

cond_table_ovino <- formattable::formattable(rank_table_ovino,
                    col.names = c("Cidade - Ranking", "Efetivo (mil cabeças)"),
                        list(efetivo = formattable::color_tile(
                            "#1f9e89", "#fde725")),
                                align = c("c", "c")
    )
formattable::as.htmlwidget(cond_table_ovino, width = 400)

ovinos <- rebanho |>
    dplyr::filter(
        abbrev_state == "RS" &
            tipo_de_rebanho == "Ovino"
            ) |>
    ggplot2::ggplot() +
        geom_sf(aes(fill = valor / 1000, na.rm = TRUE)) +
    viridis::scale_fill_viridis(discrete = FALSE) +
       theme_void() +
        labs(
            title = "Efetivo ovino do Rio Grande do Sul",
           subtitle = "IBGE [Pesquisa pecuária municipal (2021) 2023] & geobr (2019) 
            by Ítalo Monteiro ",
        fill = "Número\n[mil cabeça]") +
        theme(
            plot.title = element_text(
                face = "italic", size = 25, hjust = 0.1),
            plot.subtitle = element_text(
                family = "italic", size = 15, color = "gray50", hjust = 0.1),
            plot.caption = element_text(
                face = "italic", size = 12, color = "gray50"),
            axis.text.y = element_blank(),
            #axis.text.y = element_text(
                #size = 14, hjust = 1, family = "Fira Sans"),
            plot.margin = margin(rep(15, 4)),
            panel.background = element_blank(),
            plot.background = element_blank()
        )
ovinos       
```

```{r}
ggsave("Image/ovinos.png", plot = ovinos, dpi = 600)
```


tabela-ranking e mapa de suinos
```{r}
reb |>
    dplyr::filter(
        abbrev_state == "RS" &
            tipo_de_rebanho == "Suíno - total" & valor > 80000
    ) |>
    dplyr::mutate(cab = valor / 1000) |>
    dplyr::select(municipio, cab) |>
    dplyr::arrange(desc(cab))


rank_table_suino <- tibble::tribble(
    ~cidade,	~efetivo,
    "Santo Cristo", 154.411,
    "Frederico Westphalen", 121.592,
    "Palmitinho", 119.331,
    "Aratiba", 115.648,
    "Três Passos", 107.032,
    "Rodeio Bonito",  99.529,
    "Teutônia",  90.840,
    "Pinhal",  90.000,
    "Pinheirinho do Vale",  88.931,
    "Estrela",  82.000
)

cond_table_suino <- formattable::formattable(rank_table_suino,
                    col.names = c("Cidade - Ranking", "Efetivo (mil cabeças)"),
                        list(efetivo = formattable::color_tile(
                            "#1f9e89", "#fde725")),
                                align = c("c", "c")
    )
formattable::as.htmlwidget(cond_table_suino, width = 400)

suinos <- rebanho |> 
    dplyr::filter(
        abbrev_state == "RS" &
            tipo_de_rebanho == "Suíno - total"
            ) |>
    ggplot2::ggplot() +
        geom_sf(aes(fill = valor / 1000, na.rm = TRUE)) +
    viridis::scale_fill_viridis(discrete = FALSE) +
        theme_void() +
        labs(
            title = "Efetivo suíno do Rio Grande do Sul",
           subtitle = "IBGE [Pesquisa pecuária municipal (2021) 2023] & geobr (2019) 
            by Ítalo Monteiro ",
        fill = "Número\n[mil cabeças]") +
        theme(
            plot.title = element_text(
                face = "italic", size = 25, hjust = 0.1),
            plot.subtitle = element_text(
                family = "italic", size = 15, color = "gray50", hjust = 0.1),
            plot.caption = element_text(
                face = "italic", size = 12, color = "gray50"),
            axis.text.y = element_blank(),
            #axis.text.y = element_text(
                #size = 14, hjust = 1, family = "Fira Sans"),
            plot.margin = margin(rep(15, 4)),
            panel.background = element_blank(),
            plot.background = element_blank()
        )
suinos
```

```{r}
ggsave("Image/suinos.png", plot = suinos, dpi = 600)
```


tabela-ranking e mapa de galinhas
```{r}
reb |>
    dplyr::filter(
        abbrev_state == "RS" &
            tipo_de_rebanho == "Galináceos - galinhas" & valor > 386000
    ) |>
    dplyr::mutate(cab = valor / 1000) |>
    dplyr::select(municipio, cab) |>
    dplyr::arrange(desc(cab))


rank_table_galinha <- tibble::tribble(
    ~cidade,	~efetivo,
    "Farroupilha", 942.953,
    "Salvador do Sul", 861.161,
    "Alto Feliz", 635.676,
    "Morro Reuter", 617.178,
    "Flores da Cunha", 605.388,
    "Vacaria", 570.350,
    "Taquari", 553.000,
    "Fazenda Vilanova", 425.000,
    "Garibaldi", 397.349,
    "Vila Maria", 386.705
)

cond_table_galinha <- formattable::formattable(rank_table_galinha,
                    col.names = c("Cidade - Ranking", "Efetivo (mil cabeças)"),
                        list(efetivo = formattable::color_tile(
                            "#1f9e89", "#fde725")),
                                align = c("c", "c")
    )
formattable::as.htmlwidget(cond_table_galinha, width = 400)

galinhas <- rebanho |>
    dplyr::filter(
        abbrev_state == "RS" &
            tipo_de_rebanho == "Galináceos - galinhas"
            ) |>
    ggplot2::ggplot() +
        geom_sf(aes(fill = valor / 1000, na.rm = TRUE)) +
    viridis::scale_fill_viridis(discrete = FALSE) +
        theme_void() +
        labs(
            title = "Efetivo galináceos - galinhas do Rio Grande do Sul",
           subtitle = "IBGE [Pesquisa pecuária municipal (2021) 2023] & geobr (2019) 
            by Ítalo Monteiro ",
        fill = "Número\n[mil cabeças]") +
        theme(
            plot.title = element_text(
                face = "italic", size = 25, hjust = 0.1),
            plot.subtitle = element_text(
                family = "italic", size = 15, color = "gray50", hjust = 0.1),
            plot.caption = element_text(
                face = "italic", size = 12, color = "gray50"),
            axis.text.y = element_blank(),
            #axis.text.y = element_text(
                #size = 14, hjust = 1, family = "Fira Sans"),
            plot.margin = margin(rep(15, 4)),
            panel.background = element_blank(),
            plot.background = element_blank()
        )
galinhas
```

```{r}
ggsave("Image/galinhas.png", plot = galinhas, dpi = 600)
```

tabela-ranking e mapa de bubalino
```{r}
reb |>
    dplyr::filter(
        abbrev_state == "RS" &
            tipo_de_rebanho == "Bubalino" & valor > 1029
    ) |>
    dplyr::mutate(cab = valor / 1000) |>
    dplyr::select(municipio, cab) |>
    dplyr::arrange(desc(cab))


rank_table_bubalino <- tibble::tribble(
    ~cidade,	~efetivo,
    "Uruguaiana", 2.554,
    "Alegrete", 2.502,
    "São Gabriel", 1.699,
    "Pedras Altas", 1.404,
    "Taquara", 1.400,
    "São Nicolau", 1.392,
    "Rio Grande", 1.220,
    "Passo do Sobrado", 1.120,
    "Guaíba", 1.056,
    "General Câmara", 1.030
)

cond_table_bubalino <- formattable::formattable(rank_table_bubalino,
                    col.names = c("Cidade - Ranking", "Efetivo (mil cabeças)"),
                        list(efetivo = formattable::color_tile(
                            "#1f9e89", "#fde725")),
                                align = c("c", "c")
    )
formattable::as.htmlwidget(cond_table_bubalino, width = 400)

bubalino <- rebanho |>
    dplyr::filter(
        abbrev_state == "RS" &
            tipo_de_rebanho == "Bubalino"
            ) |>
    ggplot2::ggplot() +
        geom_sf(aes(fill = valor / 1000, na.rm = TRUE)) +
    viridis::scale_fill_viridis(discrete = FALSE) +
        theme_void() +
        labs(
            title = "Efetivo bubalino do Rio Grande do Sul",
           subtitle = "IBGE [Pesquisa pecuária municipal (2021) 2023] & geobr (2019) 
            by Ítalo Monteiro ",
        fill = "Número\n[mil cabeças]") +
        theme(
            plot.title = element_text(
                face = "italic", size = 25, hjust = 0.1),
            plot.subtitle = element_text(
                family = "italic", size = 15, color = "gray50", hjust = 0.1),
            plot.caption = element_text(
                face = "italic", size = 12, color = "gray50"),
            axis.text.y = element_blank(),
            #axis.text.y = element_text(
                #size = 14, hjust = 1, family = "Fira Sans"),
            plot.margin = margin(rep(15, 4)),
            panel.background = element_blank(),
            plot.background = element_blank()
        )
bubalino
```

```{r}
ggsave("Image/bubalino.png", plot = bubalino, dpi = 600)
```

tabela-ranking e mapa de caprino
```{r}
reb |>
    dplyr::filter(
        abbrev_state == "RS" &
            tipo_de_rebanho == "Caprino" & valor > 1029
    ) |>
    dplyr::mutate(cab = valor / 1000) |>
    dplyr::select(municipio, cab) |>
    dplyr::arrange(desc(cab))


rank_table_caprino <- tibble::tribble(
    ~cidade,	~efetivo,
    "Bagé", 6.342,
    "Santana da Boa Vista", 5.959,
    "Caçapava do Sul", 3.915,
    "Canguçu", 2.277,
    "Lavras do Sul", 1.939,
    "Pinheiro Machado", 1.780,
    "Barão do Triunfo", 1.500,
    "Piratini", 1.493,
    "Cachoeira do Sul", 1.050,
    "Gravataí", 1.040
)

cond_table_caprino <- formattable::formattable(rank_table_caprino,
                    col.names = c("Cidade - Ranking", "Efetivo (mil cabeças)"),
                        list(efetivo = formattable::color_tile(
                            "#1f9e89", "#fde725")),
                                align = c("c", "c")
    )
formattable::as.htmlwidget(cond_table_caprino, width = 400)

caprino <- rebanho |>
    dplyr::filter(
        abbrev_state == "RS" &
            tipo_de_rebanho == "Caprino"
            ) |>
    ggplot2::ggplot() +
        geom_sf(aes(fill = valor, na.rm = TRUE)) +
    viridis::scale_fill_viridis(discrete = FALSE) +
        theme_void() +
        labs(
            title = "Efetivo caprino do Rio Grande do Sul",
           subtitle = "IBGE [Pesquisa pecuária municipal (2021) 2023] & geobr (2019) 
            by Ítalo Monteiro ",
        fill = "Número\n[mil cabeças]") +
        theme(
            plot.title = element_text(
                face = "italic", size = 25, hjust = 0.1),
            plot.subtitle = element_text(
                family = "italic", size = 15, color = "gray50", hjust = 0.1),
            plot.caption = element_text(
                face = "italic", size = 12, color = "gray50"),
            axis.text.y = element_blank(),
            #axis.text.y = element_text(
                #size = 14, hjust = 1, family = "Fira Sans"),
            plot.margin = margin(rep(15, 4)),
            panel.background = element_blank(),
            plot.background = element_blank()
        )
caprino
```

```{r}
ggsave("Image/caprino.png", plot = caprino, dpi = 600)
```

tabela-ranking e mapa de codornas
```{r}
reb |>
    dplyr::filter(
        abbrev_state == "RS" &
            tipo_de_rebanho == "Codornas" & valor > 17000
    ) |>
    dplyr::mutate(cab = valor / 1000) |>
    dplyr::select(municipio, cab) |>
    dplyr::arrange(desc(cab))


rank_table_codornas <- tibble::tribble(
    ~cidade,	~efetivo,
    "Farroupilha", 113.000,
    "Fazenda Vilanova",  80.000,
    "General Câmara",  60.000,
    "Alto Feliz",  58.608,
    "Lajeado",  52.330,
    "Sapiranga",  47.000,
    "Gaurama",  38.000,
    "Santa Clara do Sul",  22.000,
    "Paverama",  20.000,
    "Dois Irmãos",  18.000
)

cond_table_codornas <- formattable::formattable(rank_table_codornas,
                    col.names = c("Cidade - Ranking", "Efetivo (mil cabeças)"),
                        list(efetivo = formattable::color_tile(
                            "#1f9e89", "#fde725")),
                                align = c("c", "c")
    )
formattable::as.htmlwidget(cond_table_codornas, width = 400)

codornas <- rebanho |>
    dplyr::filter(
        abbrev_state == "RS" &
            tipo_de_rebanho == "Codornas"
            ) |>
    ggplot2::ggplot() +
        geom_sf(aes(fill = valor / 1000, na.rm = TRUE)) +
    viridis::scale_fill_viridis(discrete = FALSE) +
        theme_void() +
        labs(
            title = "Efetivo codornas do Rio Grande do Sul",
           subtitle = "IBGE [Pesquisa pecuária municipal (2021) 2023] & geobr (2019) 
            by Ítalo Monteiro ",
        fill = "Número\n[mil cabeças]") +
        theme(
            plot.title = element_text(
                face = "italic", size = 25, hjust = 0.1),
            plot.subtitle = element_text(
                family = "italic", size = 15, color = "gray50", hjust = 0.1),
            plot.caption = element_text(
                face = "italic", size = 12, color = "gray50"),
            axis.text.y = element_blank(),
            #axis.text.y = element_text(
                #size = 14, hjust = 1, family = "Fira Sans"),
            plot.margin = margin(rep(15, 4)),
            panel.background = element_blank(),
            plot.background = element_blank()
        )
codornas
```

```{r}
ggsave("Image/codornas.png", plot = codornas, dpi = 600)
```
